# Generated by Django 5.0.4 on 2024-05-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='watchAgain',
            field=models.BooleanField(default=False),
        ),
    ]
