# Generated by Django 5.0.4 on 2024-05-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_reviews_watchagain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='watchAgain',
            field=models.BooleanField(),
        ),
    ]
